---@toc neotest-nix.contents

---@mod neotest-nix A Neotest adapter for running Nix tests
---@brief [[
---
---neotest-nix is a Neotest adapter for running Nix tests directly from Neovim.
---It discovers two kinds of tests in a flake-based project and runs them in
---place:
---
---  - Flake checks: `checks.<system>.<name>` derivations, including NixOS VM
---    tests with a `testScript`. Run with `nix`.
---  - nix-unit tests: attribute sets shaped `{ expr = ...; expected = ...; }`
---    (or `expectedError`). Run with `nix-unit`.
---
---Run |:checkhealth| neotest-nix to verify your setup.
---@brief ]]

---@mod neotest-nix.requirements Requirements
---@brief [[
---  - Neovim >= 0.11
---  - Nix on `PATH`. The adapter passes `--extra-experimental-features` for
---    its own `nix` calls, so these features do not need to be enabled globally
---    in your Nix config.
---  - `nix-unit` on PATH (only for nix-unit tests)
---  - Plugin dependencies: `neotest` and `nvim-nio`
---  - The `nix` tree-sitter grammar on your runtimepath (a `parser/nix.so`).
---    Positions are parsed through Neovim's built-in |vim.treesitter|, so any
---    source of the grammar works.
---@brief ]]

---@mod neotest-nix.installation Installation
---@brief [[
---With lazy.nvim, register the adapter on Neotest: >lua
---    {
---      "nvim-neotest/neotest",
---      dependencies = {
---        "nvim-neotest/nvim-nio",
---        "nvim-treesitter/nvim-treesitter",
---        "khaneliman/neotest-nix",
---      },
---      opts = function()
---        return {
---          adapters = {
---            require("neotest-nix"),
---          },
---        }
---      end,
---    }
---<
---Or configure Neotest directly: >lua
---    require("neotest").setup({
---      adapters = { require("neotest-nix") },
---    })
---<
---The repository also ships an overlay exposing `vimPlugins.neotest-nix` for
---Nix-based configurations.
---@brief ]]

---@mod neotest-nix.usage Usage
---@brief [[
---Open a `flake.nix` (or a `*.nix` file whose name contains `test` and which
---holds nix-unit assertions) and use the standard Neotest commands: >lua
---    require("neotest").run.run()                   -- nearest test
---    require("neotest").run.run(vim.fn.expand("%")) -- whole file
---    require("neotest").summary.toggle()            -- test tree
---<
---@brief ]]

---@mod neotest-nix.configuration Configuration
---@brief [[
---All options are optional. Defaults shown: >lua
---    require("neotest-nix")({
---      parser_runtime_paths = nil,
---      discover_eval_checks = false,
---      eval_outputs = { { attr = "checks" } },
---      nix_unit_flakes = nil,
---      nixpkgs_mode = nil,
---    })
---<
---                                    *neotest-nix-config-parser_runtime_paths*
---`parser_runtime_paths`        `string[]?` (default `nil`)
---    Extra runtimepath roots containing `parser/nix.so`, in case the nix
---    tree-sitter grammar is not already on your runtimepath.
---
---                                    *neotest-nix-config-discover_eval_checks*
---`discover_eval_checks`        `boolean?` (default `false`)
---    Evaluate the flake to discover generated outputs that are not visible in
---    the source (e.g. checks produced by a function). Off by default because it
---    shells out to `nix eval`.
---
---                                            *neotest-nix-config-eval_outputs*
---`eval_outputs`                `neotest-nix.EvalOutput[]?`
---                              (default `{ { attr = "checks" } }`)
---    Which outputs to enumerate per system when `discover_eval_checks` is
---    enabled. Each entry is a |neotest-nix.EvalOutput|:
---    `{ attr = <output>, match = <lua pattern?> }`.
---
---                                         *neotest-nix-config-nix_unit_flakes*
---`nix_unit_flakes`             `neotest-nix.NixUnitFlake[]?` (default `nil`)
---    nix-unit tests defined in a function- or `let`-wrapped file (e.g.
---    `{ self, lib }: { testFoo = ...; }`) cannot be evaluated standalone, so
---    they are run through their flake output with `nix-unit --flake <flake>`,
---    which reports per-attribute results. The output is auto-detected by
---    evaluating the flake and matching the suite's test names, so no
---    configuration is usually needed. Set this only to override detection or
---    when the suite lives somewhere detection cannot find (e.g. nested under a
---    non-top-level output): >lua
---        nix_unit_flakes = { { path = "lib/tests", flake = ".#tests" } },
---<
---    `path` may be absolute or relative to the flake root, and matches the file
---    itself or any directory containing it.
---
---                                            *neotest-nix-config-nixpkgs_mode*
---`nixpkgs_mode`                `boolean?` (default `nil`)
---    Controls Nixpkgs-style discovery, which runs tests with legacy commands
---    (`nix-build -A`) that evaluate the working tree in place instead of copying
---    the whole tree to the store like a flake build. Left unset, it auto-detects
---    a Nixpkgs checkout (a tree with `pkgs/by-name`, `lib`, and `nixos` or
---    `pkgs/top-level/all-packages.nix`). Set `true` to force it (e.g. on a fork
---    without the usual markers) or `false` to disable it and treat the project
---    as a plain flake. When active, a `pkgs/by-name/<shard>/<name>/package.nix`
---    file exposes its `passthru.tests` entries, run with
---    `nix-build -A <name>.tests.<test>`.
---@brief ]]

---@mod neotest-nix.discovery Discovery
---@brief [[
---  - `flake.nix` is always treated as a test file.
---  - Any other `*.nix` file is a test file only when its name OR its immediate
---    parent directory contains `test` AND it contains a nix-unit assertion
---    (`expr` plus `expected` or `expectedError`). This covers both
---    `foo_test.nix` and the common `tests/default.nix` layout.
---  - nix-unit assertions are discovered when their value has nix-unit shape
---    (`expr` plus `expected` or `expectedError`). Attribute names do not need
---    a `test` prefix; `addition` and `testAddition` both appear.
---  - Positions are parsed from source with tree-sitter. When
---    `discover_eval_checks` is enabled, flake outputs are additionally
---    enumerated via `nix eval` and merged into the tree, so checks generated at
---    evaluation time still show up.
---  - In a Nixpkgs checkout (see |neotest-nix-config-nixpkgs_mode|), a
---    `pkgs/by-name/<shard>/<name>/package.nix` file is a test file: its
---    `passthru.tests` members are parsed from source and run with
---    `nix-build -A <name>.tests.<test>`.
---@brief ]]

---@mod neotest-nix.limitations Limitations
---@brief [[
---  - Tests are only discovered inside a flake project. With no `flake.nix` at
---    or above the file, the adapter does not apply.
---  - nix-unit runners evaluate the flake with `builtins.getFlake`, which sees
---    only git-tracked files. A brand-new, untracked `flake.nix` or test file is
---    invisible until it is staged or committed.
---  - Running a nix-unit suite (a `tests`-style namespace, or a function- or
---    `let`-wrapped file) runs the whole suite via `nix-unit --flake`, since it
---    has no single-attribute filter — every attribute in that output reports a
---    result.
---  - Running a whole `flake.nix` that mixes checks and nix-unit tests runs
---    `nix flake check`, which does not execute nix-unit suites. Run the nix-unit
---    namespace (or an individual test) to exercise them.
---  - Whole-suite runs use `nix-unit --flake`, which evaluates in pure mode and
---    therefore needs a committed `flake.lock` with every input locked. On a
---    flake whose inputs are not locked the run fails with `cannot update
---    unlocked flake input`. Individual tests run via `--expr` and are not
---    affected. Commit a lock file to run suites.
---  - Nixpkgs `passthru.tests` are discovered by a static parse, so tests added
---    by `inherit` or computed at evaluation time are not listed. Running the
---    package file (or its `tests` group) still builds `<name>.tests`, which
---    covers them.
---  - Only by-name packages that declare `passthru.tests` are treated as test
---    files; the rest of Nixpkgs' packages are skipped so the tree stays small.
---    On a checkout this large, also consider Neotest's own
---    `discovery = { enabled = false }` so it processes open buffers instead of
---    walking the whole tree.
---@brief ]]

---@mod neotest-nix.troubleshooting Troubleshooting
---@brief [[
---For slow or surprising discovery, enable debug logging by setting the
---`NEOTEST_NIX_DEBUG` environment variable (to any non-empty value other than
---`0`) or `vim.g.neotest_nix_debug = true` before discovery runs. The adapter
---then records timing for each parsed file to `neotest-nix.log` under your
---Neovim log directory (`:echo stdpath('log')`). This is the quickest way to
---see how many files discovery touches and how long parsing each one costs.
---@brief ]]

---@mod neotest-nix.health Health
---@brief [[
---Run |:checkhealth| neotest-nix to confirm the Neovim version, the `neotest`
---and `nvim-nio` plugins, the `nix` and `nix-unit` executables, and the `nix`
---tree-sitter grammar are all in place. It also reports unknown or wrong-typed
---configuration keys.
---@brief ]]

-- Annotation-only module: nothing requires it at runtime. It is the single
-- source vimcats compiles into doc/neotest-nix.txt (see CONTRIBUTING), and it
-- defines the public config types that lua-language-server resolves across the
-- workspace (init.lua references them by name).
local M = {}

---A single flake output to enumerate per system during eval-based discovery.
---See |neotest-nix.configuration| for details.
---@class neotest-nix.EvalOutput
---@field attr string Flake output to enumerate (e.g. "checks").
---@field match? string Lua pattern filtering attribute names.

---Maps a function/let-wrapped nix-unit file (or directory) to the flake
---installable that exposes its applied test attribute set, so the adapter can
---run it with `nix-unit --flake <flake>`. See |neotest-nix.configuration|.
---@class neotest-nix.NixUnitFlake
---@field path string File or directory holding the tests (absolute, or relative to the flake root).
---@field flake string Flake installable passed to `nix-unit --flake` (e.g. ".#tests").

---Adapter configuration. Every field is optional; see |neotest-nix.configuration|.
---@class neotest-nix.Config
---@field parser_runtime_paths? string[] Extra runtimepath roots containing parser/nix.so.
---@field discover_eval_checks? boolean Evaluate the flake to discover generated outputs.
---@field eval_outputs? neotest-nix.EvalOutput[] Outputs to enumerate when discovery is on.
---@field nix_unit_flakes? neotest-nix.NixUnitFlake[] Run wrapped nix-unit suites via a flake installable.
---@field nixpkgs_mode? boolean Force (true) or disable (false) legacy Nixpkgs handling; nil auto-detects.

return M
